[package]
name = "context"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
feather = { workspace = true, features = ["json","log"] }
r2d2 ={ workspace = true}
r2d2_sqlite ={ workspace = true, features = ["bundled"]}
serde_json = { workspace = true }